# Generated by Django 5.2.7 on 2025-10-09 22:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('annual', 'Anual'), ('semester', 'Semestral'), ('monthly', 'Mensual'), ('project', 'Por Proyecto')], max_length=20, verbose_name='Tipo de Meta')),
                ('target_hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Horas Objetivo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meta de Horas',
                'verbose_name_plural': 'Metas de Horas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Horas')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('activity_description', models.TextField(verbose_name='Descripción de la Actividad')),
                ('skills_developed', models.TextField(blank=True, verbose_name='Habilidades Desarrolladas')),
                ('impact_description', models.TextField(blank=True, verbose_name='Descripción del Impacto')),
                ('supervisor_name', models.CharField(max_length=200, verbose_name='Nombre del Supervisor')),
                ('supervisor_contact', models.CharField(max_length=200, verbose_name='Contacto del Supervisor')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de Revisión')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour_logs', to='applications.application', verbose_name='Aplicación')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_logs', to='projects.project', verbose_name='Proyecto')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hour_logs', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hour_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Horas',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourLogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('attendance', 'Lista de Asistencia'), ('certificate', 'Certificado'), ('photo', 'Fotografía'), ('report', 'Reporte'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='hour_log_documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hour_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hours.hourlog', verbose_name='Registro de Horas')),
            ],
            options={
                'verbose_name': 'Documento de Registro de Horas',
                'verbose_name_plural': 'Documentos de Registros de Horas',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HourSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total de Horas')),
                ('approved_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Aprobadas')),
                ('pending_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Pendientes')),
                ('rejected_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Rechazadas')),
                ('projects_count', models.PositiveIntegerField(default=0, verbose_name='Número de Proyectos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Resumen de Horas',
                'verbose_name_plural': 'Resúmenes de Horas',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
