# Generated by Django 5.2.7 on 2025-10-09 22:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('motivation', models.TextField(help_text='Explica por qué quieres participar en este proyecto', verbose_name='Motivación')),
                ('relevant_experience', models.TextField(blank=True, help_text='Describe tu experiencia relacionada con este proyecto', verbose_name='Experiencia Relevante')),
                ('available_hours_per_week', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Horas Disponibles por Semana')),
                ('start_date_preference', models.DateField(verbose_name='Fecha de Inicio Preferida')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de Revisión')),
                ('hours_completed', models.PositiveIntegerField(default=0, verbose_name='Horas Completadas')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project', verbose_name='Proyecto')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('cv', 'Currículum Vitae'), ('transcript', 'Expediente Académico'), ('recommendation', 'Carta de Recomendación'), ('portfolio', 'Portafolio'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='application_documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='Aplicación')),
            ],
            options={
                'verbose_name': 'Documento de Aplicación',
                'verbose_name_plural': 'Documentos de Aplicaciones',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_submitted', 'Aplicación Enviada'), ('application_reviewed', 'Aplicación Revisada'), ('application_approved', 'Aplicación Aprobada'), ('application_rejected', 'Aplicación Rechazada'), ('project_started', 'Proyecto Iniciado'), ('project_completed', 'Proyecto Completado'), ('hours_updated', 'Horas Actualizadas')], max_length=30, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application', verbose_name='Aplicación')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación de Aplicación',
                'verbose_name_plural': 'Notificaciones de Aplicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación (1-10)')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('recommendation', models.CharField(choices=[('approve', 'Aprobar'), ('reject', 'Rechazar'), ('interview', 'Entrevista')], max_length=20, verbose_name='Recomendación')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='applications.application', verbose_name='Aplicación')),
                ('evaluator', models.ForeignKey(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='application_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
            ],
            options={
                'verbose_name': 'Evaluación de Aplicación',
                'verbose_name_plural': 'Evaluaciones de Aplicaciones',
                'ordering': ['-evaluated_at'],
                'unique_together': {('application', 'evaluator')},
            },
        ),
    ]
