# Generated by Django 5.2.7 on 2025-11-04 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_temp_password_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scholarship_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, help_text='Porcentaje de beca (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Beca'),
        ),
        migrations.AddField(
            model_name='user',
            name='scholarship_type',
            field=models.CharField(blank=True, default='KEY EXCELLENCE', help_text='Nombre de la beca asignada al estudiante', max_length=100, null=True, verbose_name='Tipo de Beca'),
        ),
    ]
