# Generated by Django 5.2.7 on 2025-10-09 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#2196F3', help_text='Color en formato hexadecimal (ej: #2196F3)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (ej: education, healthcare)', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Proyecto',
                'verbose_name_plural': 'Categorías de Proyectos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('max_hours', models.PositiveIntegerField(help_text='Máximo de horas que se pueden registrar en este proyecto', verbose_name='Horas Máximas')),
                ('hour_assignment', models.CharField(choices=[('automatic', 'Automática'), ('manual', 'Manual')], default='automatic', max_length=20, verbose_name='Asignación de Horas')),
                ('automatic_hours', models.PositiveIntegerField(blank=True, help_text='Horas que se asignan automáticamente al completar el proyecto', null=True, verbose_name='Horas Automáticas')),
                ('visibility', models.CharField(choices=[('unpublished', 'No Publicado'), ('convocatoria', 'Convocatoria'), ('published', 'Publicado')], default='unpublished', max_length=20, verbose_name='Visibilidad')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Máximo de Participantes')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participantes Actuales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('members', models.ManyToManyField(blank=True, related_name='participating_projects', to=settings.AUTH_USER_MODEL, verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('description', 'Descripción'), ('requirements', 'Requisitos'), ('manual', 'Manual'), ('template', 'Plantilla'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Documento de Proyecto',
                'verbose_name_plural': 'Documentos de Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Requisito')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Requisito de Proyecto',
                'verbose_name_plural': 'Requisitos de Proyectos',
                'ordering': ['-is_mandatory', 'title'],
            },
        ),
    ]
